#!/bin/sh

# Récupérer nom du profile
if [ -z $1 ]; then
	echo -n "Nom du profile : "
	read NAMEOFPROFILE
else
	NAMEOFPROFILE=$1
fi

firefox -P -CreateProfile "$NAMEOFPROFILE"

echo "#!/bin/sh
# Script created by newFirefoxProfile at `date -I`.

firefox -new-instance -P $NAMEOFPROFILE" > ~/.local/bin/brow${NAMEOFPROFILE}

chmod +x ~/.local/bin/brow${NAMEOFPROFILE}
